# XuanTahititan
+ Response 200 (application/json)
{
  "status": "ok",
  "totalResults": 10,
  "articles": [
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Carly Page",
      "title": "Prelude raises $24M to help organizations harden their cybersecurity defenses",
      "description": "The Series A round will help the company build out its engineering team.",
      "url": "https://techcrunch.com/2022/04/12/prelude-series-a-cybersecurity-defenses/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/IMG-0525.jpg?w=533",
      "publishedAt": "2022-04-12T12:20:33Z",
      "content": "Prelude, a Washington D.C-based startup that helps organizations harden their cyber defenses through the use of autonomous red-teaming, has secured $24 million in Series A funding.\r\nPrelude which des… [+2780 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Ingrid Lunden",
      "title": "Observe.ai raises $125M, adding Zoom as an investor, to supercharge the contact center market",
      "description": "Contact centers play a key part in call a company engages with customers, amounting to what is a $400 billion market globally. Today, a company that believes it can improve how agents work within them using AI is announcing a big round of funding. Observe.ai …",
      "url": "https://techcrunch.com/2022/04/12/observe-ai-raises-125m-adding-zoom-as-an-investor-to-supercharge-the-contact-center-market/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2021/01/Hiretual-Techcrunch_article_2_image_2.jpeg?w=764",
      "publishedAt": "2022-04-12T12:02:12Z",
      "content": "Contact centers play a key part in call a company engages with customers, amounting to what is a $400 billion market globally. Today, a company that believes it can improve how agents work within the… [+5081 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Anita Ramaswamy",
      "title": "Glow Labs raises seed round to help NFT creators reward their loyal customers",
      "description": "Forerunner, Female Founders Fund are among the venture firms backing blockchain loyalty rewards software Glow Labs",
      "url": "https://techcrunch.com/2022/04/12/glow-labs-raises-seed-round-to-help-nft-creators-reward-their-loyal-customers/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/BANNER4.jpg?w=718",
      "publishedAt": "2022-04-12T12:00:58Z",
      "content": "The NFT market was worth $41 billion at the end of last year — nearly as large as the conventional art market by some estimates — and it’s expected to nearly double in size by the end of 2022, accord… [+5688 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Brian Heater",
      "title": "Miso Robotics brings a new coffee monitoring system to Panera",
      "description": "Miso made a name for itself with the hamburger-cooking robot, Flippy. With new coffee capabilities, Miso’s branching out with another big chain: Panera Bread",
      "url": "https://techcrunch.com/2022/04/12/miso-robotics-brings-a-new-coffee-monitoring-system-to-panera/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/DSC09902.jpg?w=600",
      "publishedAt": "2022-04-12T12:00:37Z",
      "content": "Miso made a name for itself with the hamburger-cooking robot, Flippy. The company has done a fine job diversifying itself in the worlds fast food kitchens with the additions of Sippy and Chippy, aime… [+1562 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Romain Dillet",
      "title": "Montonio is building the payment and checkout solution to rule them all",
      "description": "Meet Montonio, an e-commerce checkout solution created by a small startup based in Tallinn, Estonia. The company just raised a $12 million Series A funding round (€11 million) led by Index Ventures. It wants to become the only tech partner you need to run a s…",
      "url": "https://techcrunch.com/2022/04/12/montonio-is-building-the-payment-and-checkout-solution-to-rule-them-all/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/MontonioCEO.jpg?w=600",
      "publishedAt": "2022-04-12T11:20:12Z",
      "content": "Meet Montonio, an e-commerce checkout solution created by a small startup based in Tallinn, Estonia. The company just raised a $12 million Series A funding round (11 million) led by Index Ventures. I… [+3375 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Manish Singh",
      "title": "India’s Meesho likely to postpone new funding amid market uncertainty",
      "description": "Meesho has let go over 150 employees and is looking to eliminate at least as many more positions as the Indian social commerce attempts to streamline its operations following an ongoing struggle to put together a new funding round at favorable terms, sources …",
      "url": "https://techcrunch.com/2022/04/12/indias-meesho-likely-to-postpone-new-funding-amid-market-uncertainty/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2020/11/GettyImages-536118200-1.jpg?w=599",
      "publishedAt": "2022-04-12T11:18:52Z",
      "content": "Meesho has let go over 150 employees and is looking to eliminate at least as many more positions as the Indian social commerce attempts to streamline its operations following an ongoing struggle to p… [+2350 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Zack Whittaker",
      "title": "Autonomous robots used in hundreds of hospitals at risk of remote hijacks",
      "description": "The five flaws allowed anyone to view real-time robot camera feeds and remotely control the robots.",
      "url": "https://techcrunch.com/2022/04/12/aethon-robots-hospitals-hijacks/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/GettyImages-474383260.jpg?w=601",
      "publishedAt": "2022-04-12T11:00:53Z",
      "content": "A decade ago security researcher Barnaby Jack famously wirelessly hacked a hospital insulin pump live on stage in front of hundreds of people to demonstrate how easily it could be compromised to deli… [+3759 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Ingrid Lunden",
      "title": "Bosch picks up Five.ai after the self-driving startup pivoted to B2B and then put itself up for sale",
      "description": "Consolidation is moving ahead in the world of autonomous driving, with the latest development coming out of Europe. Today, Bosch announced that it would be acquiring Five.ai, the autonomous driving startup that started with big ambitions to build and operate …",
      "url": "https://techcrunch.com/2022/04/12/bosch-picks-up-five-ai-after-the-self-driving-startup-that-pivoted-to-b2b-put-itself-up-for-sale/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/five-ai.jpg?w=556",
      "publishedAt": "2022-04-12T10:27:07Z",
      "content": "Consolidation is moving ahead in the world of autonomous driving, with the latest development coming out of Europe. Today, Bosch announced that it would be acquiring Five.ai, the autonomous driving s… [+4069 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Tage Kene-Okafor",
      "title": "Egypt’s Pylon gets $19M to scale software for water and electricity distribution companies",
      "description": "Pylon, an Egyptian infrastructure management platform for water and electricity companies in emerging markets, has raised a $19 million seed round. The round, a combination of debt and equity, was led by U.S.-based Endure Capital, which is backed by British I…",
      "url": "https://techcrunch.com/2022/04/12/egypts-pylon-gets-19m-to-scale-software-for-water-and-electricity-distribution-companies/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/PhotoPictureResizer_220412_083332880_crop_750x535.jpg?w=561",
      "publishedAt": "2022-04-12T08:12:35Z",
      "content": "Pylon, an Egyptian infrastructure management platform for water and electricity companies in emerging markets, has raised a $19 million seed round.\r\nThe round, a combination of debt and equity, was l… [+5866 chars]"
    },
    {
      "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
      },
      "author": "Christine Hall",
      "title": "Choco gets its horn amid mission to remove food waste from supply chain",
      "description": "Choco's software digitizes ordering, supply chain and communications for suppliers and restaurants so they can better monitor supply and demand.",
      "url": "https://techcrunch.com/2022/04/11/choco-unicorn-food-waste-supply-chain/",
      "urlToImage": "https://techcrunch.com/wp-content/uploads/2022/04/App-screens_EN_Graphic-mockup.png?w=715",
      "publishedAt": "2022-04-12T06:01:20Z",
      "content": "Choco, a company aimed at building a more sustainable food system for restaurants and suppliers, brought in another big raise this time $111 million in what it’s calling a Series B2 round to boost it… [+2908 chars]"
    }
  ]
}